---
sudo: required

env:
  - distribution: ubuntu
    version: focal

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm -f Dockerfile.${version} -t ${distribution}-${version}:ansible .'

script:
  - echo "$VAULT_PASSWORD" >> ${PWD}/vault_pass.txt
  - tail ${PWD}/vault_pass.txt
  - container_id=$(mktemp)
  - 'sudo docker run -itd --privileged --volume="${PWD}":/ansible ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" ansible-playbook --verbose --syntax-check /ansible/main.yml -i /ansible/hosts --vault-password-file /ansible/vault_pass.txt'
  - 'sudo docker exec "$(cat ${container_id})" ansible-playbook --verbose --skip-tags network,snap,youtube /ansible/main.yml -i /ansible/hosts --vault-password-file /ansible/vault_pass.txt'
  - 'sudo docker rm -f "$(cat ${container_id})"'
