---
sudo: required

env:
  - distribution: ubuntu
    version: bionic

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm -f travis/Dockerfile.${distribution}-${version} -t ${distribution}-${version}:ansible .'

script:
  - container_id=$(mktemp)
  - 'sudo docker run -itd --privileged --volume="${PWD}":/ansible ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" ansible-playbook --verbose --syntax-check /ansible/main.yml -i /ansible/hosts'
  - 'sudo docker exec "$(cat ${container_id})" ansible-playbook --verbose --skip-tags network /ansible/main.yml -i /ansible/hosts'
  - 'sudo docker rm -f "$(cat ${container_id})"'