version: '3'
services:
  bionic:
    build:
      context: .
      dockerfile: Dockerfile.bionic
    volumes:
    - .:/ansible
    working_dir: /ansible
    stdin_open: true
    tty: true
  focal:
    build:
      context: .
      dockerfile: Dockerfile.focal
    volumes:
      - .:/ansible
    working_dir: /ansible
    stdin_open: true
    tty: true
