---
- name: Configure my laptop
  hosts: all
  become: yes
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  vars_files:
    - ./external_vars.yml
  pre_tasks:
    - name: get the running username
      become: false
      command: whoami
      register: whoami
      tags:
        - always
    - name: Set a fact with the username
      set_fact:
        login_user: "{{ whoami.stdout }}"
      tags:
        - always
    - name: Install pip
      apt:
        name: pip
        update_cache: yes
      tags:
        - always
  tasks:
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/build-tools.yml
    - import_tasks: tasks/music.yml
    - import_tasks: tasks/bash.yml
    - import_tasks: tasks/bitwarden.yml
    - import_tasks: tasks/chrome.yml
    - import_tasks: tasks/clamav.yml
    - import_tasks: tasks/dev-tools.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/image-tools.yml
    - import_tasks: tasks/ibus.yml
    - import_tasks: tasks/network-tools.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/open-jdk.yml
    - import_tasks: tasks/peek.yml
    - import_tasks: tasks/tools.yml
    - import_tasks: tasks/video.yml
    - import_tasks: tasks/vim.yml
    - import_tasks: tasks/settings.yml
