---
- name: configure my personal computer
  hosts: localhost
  become: yes
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  vars_files:
    - conf.yml.example
  roles:
    - role: git
      mailaddress: "{{ mail_address }}"
      gitname: "{{ git_name }}"
      home_dir: "{{ local_home }}"
    - role: vim
      home_dir: "{{ local_home }}"
    - role: build-tools
    - role: javascript-tools
    - role: ruby-tools
    - role: php
    - role: python
    - role: clamav # open source antivirus engine for detecting trojans, viruses, malware & other malicious threats
    - role: video-tools
    - role: gimp
    - role: asunder
    - role: peek # Simple animated GIF screen recorder
    - role: jhead # Digicam JPEG Exif header manipulation tool
    - role: tools
    - role: mysql
    - role: audacity # cross-platform audio software
    - role: keepassx
    - role: openjdk
    - role: network-tools
    - role: clementine # modern music player and library organizer
    - role: bash
    - role: jd2ch
    - role: ibus-mozc
    - role: theme
    - role: inkscape
