---
- name: Configure my laptop
  hosts: all
  become: yes
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  tasks:
    - import_tasks: tasks/asunder.yml
    - import_tasks: tasks/audacity.yml
    - import_tasks: tasks/bash.yml
    - import_tasks: tasks/build-tools.yml
    - import_tasks: tasks/clamav.yml
    - import_tasks: tasks/dev-tools.yml
    - import_tasks: tasks/gimp.yml
    - import_tasks: tasks/git.yml
    - import_tasks: tasks/ibus.yml
    - import_tasks: tasks/inkscape.yml
    - import_tasks: tasks/jhead.yml
    - import_tasks: tasks/mysql.yml
    - import_tasks: tasks/network-tools.yml
    - import_tasks: tasks/open-jdk.yml
    - import_tasks: tasks/peek.yml
    - import_tasks: tasks/theme.yml
    - import_tasks: tasks/tools.yml
    - import_tasks: tasks/video.yml
    - import_tasks: tasks/vim.yml
