---
- name: configure my personal computer
  hosts: localhost
  become: yes
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  vars_files:
    - conf.yml
  roles:
    - role: git
      mailaddress: "{{ mail_address }}"
      git_name: "{{ git_name }}"
      home_dir: "{{ local_home }}"
    - role: vim
      home_dir: "{{ local_home }}"
    - role: node
    - role: clamav
    - role: firewall
    - role: makemkv
    - role: ruby
    - role: php
    - role: smplayer
    - role: gimp
    - role: asunder
    - role: python
    - role: peek
    - role: build-tools
    - role: k8s
    - role: devede
    - role: jhead
    - role: dconf-editor
    - role: htop
    - role: mysql
    - role: whois
    - role: apache2-utils
    - role: audacity
    - role: keepassx
    - role: openjdk
    - role: speedtest-cli
    - role: clementine
    - role: bash

