---
- name: configure my personal computer
  hosts: localhost
  become: yes
  vars:
    local_home: "{{ lookup('env','HOME') }}"
  vars_files:
    - conf.yml.example
  roles:
    - role: git
      mailaddress: "{{ mail_address }}"
      gitname: "{{ git_name }}"
      home_dir: "{{ local_home }}"
    - role: vim
      home_dir: "{{ local_home }}"
    - role: node_javascript
    - role: clamav # open source antivirus engine for detecting trojans, viruses, malware & other malicious threats
    - role: firewall
    - role: makemkv
    - role: php
    - role: smplayer
    - role: gimp
    - role: asunder
    - role: python
    - role: peek # Simple animated GIF screen recorder
    - role: build-tools
    - role: devede # free, open-source Video to DVD converter
    - role: jhead # Digicam JPEG Exif header manipulation tool
    - role: dconf-editor # ubuntu setting tool
    - role: htop
    - role: mysql
    - role: whois
    - role: apache2-utils
    - role: audacity # cross-platform audio software
    - role: keepassx
    - role: openjdk
    - role: network-tools
    - role: clementine # modern music player and library organizer
    - role: bash
    - role: jd2ch
    - role: ffmpeg
    - role: virtualbox
    - role: ukuu
    - role: ibus-mozc

