---
# tasks file for bash
- name: add bash alias
  blockinfile:
    path: "{{ local_home }}/.bash_aliases"
    create: true
    block: |
      alias purejpg='jhead -purejpg'
      alias globalip='curl httpbin.org/ip'
      alias dc='docker-compose'
  tags: bash
