---
- name: download linux brew from repository
  git:
    repo: https://github.com/Homebrew/brew
    dest: "{{ local_home }}/.linuxbrew/Homebrew"
  tags: brew

- name: mkdir linuxbrew
  file:
    path: "{{ local_home }}/.linuxbrew/bin"
    state: directory
  tags: brew

- name: link linuxbrew symlink
  file:
    state: link
    src: "{{ local_home }}/.linuxbrew/Homebrew/bin/brew"
    dest: "{{ local_home }}/.linuxbrew/bin/brew"
  tags: brew

- name: add brew to PATH
  blockinfile:
    path: "{{ local_home }}/.bashrc"
    create: false
    block: |
      export PATH="$HOME/.linuxbrew/bin:$PATH"
      export LD_LIBRARY_PATH="$HOME/.linuxbrew/lib:$LD_LIBRARY_PATH"
  tags: brew

