---
- name: add apt key for Google Chrome
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
  tags: chrome

- apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome
  tags: chrome

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    update_cache: yes
  tags: chrome

