---
- name: install dev tools from snap classic channel
  snap:
    name:
      - kubectl
      - helm
      - android-studio
      - google-cloud-sdk
      - hugo
    classic: true
  tags: snap

- name: install dev tools from snap beta channel
  snap:
    name:
      - mysql-workbench-community
    channel: beta
  tags: snap
