---
- name: install docker.io
  apt:
    name: docker.io
    update_cache: yes
  when: ansible_distribution_release != 'bionic'
  tags:
    - docker

- name: enable docker
  systemd:
    name: docker
    enabled: yes
  when: ansible_distribution_release != 'bionic'
  tags:
    - docker

- name: give user administrative privileges to docker
  user:
    name: "{{ login_user }}"
    group: docker
  when: ansible_distribution_release != 'bionic'
  tags:
    - docker
