---
- name: install docker
  snap:
    name: docker
  tags:
    - docker
    - snap

- name: add docker group
  group:
    name: docker
    system: yes
    state: present
  tags:
    - docker

- name: give user administrative privileges to docker
  user:
    name: "{{ login_user }}"
    group: docker
  tags:
    - docker
