---
- name: add git repository
  apt_repository:
    repo: "ppa:git-core/ppa"
  tags: git

- name: add meld repository
  apt_repository:
    repo: "ppa:sicklylife/ppa"
  tags: git

- name: install git and other tools
  apt:
    name: ['git','git-gui','meld','git-flow']
    update_cache: yes
  tags: git

- git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"
  become: no
  tags: git

- git_config:
    name: user.email
    scope: global
    value: "{{ git_mail_address }}"
  become: no
  tags: git

- git_config:
    name: diff.tool
    scope: global
    value: meld
  become: no
  tags: git

- git_config:
    name: merge.tool
    scope: global
    value: meld
  become: no
  tags: git

- git_config:
    name: alias.lol
    scope: global
    value: log --graph --decorate --pretty=oneline --all --abbrev-commit
  become: no
  tags: git

- git_config:
    name: push.default
    scope: global
    value: simple
  become: no
  tags: git

- git_config:
    name: pull.ff
    scope: global
    value: only
  become: no
  tags: git

- name: place gitignore file
  template:
    src: "../templates/.gitignore.j2"
    dest: "{{ local_home }}/.gitignore"
  become: no
  tags: git

- git_config:
    name: core.excludesfile
    scope: global
    value: "{{ local_home }}/.gitignore"
  become: no
  tags: git

- name: Install Git Prompt
  get_url:
    url: https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh
    dest: "{{ local_home }}/git-prompt.sh"
  become: no
  tags: git

- name: Install Git Prompt
  blockinfile:
    path: "{{ local_home }}/.bashrc"
    create: false
    block: |
      PS1="\[\033[1;32m\]\$(date +%Y/%m/%d_%H:%M:%S)\[\033[0m\] \[\033[33m\]\H:\w\n\[\033[0m\][\u@ \W]\[\033[36m\]\$(__git_ps1)\[\033[00m\]\$ "

      #
      # git-completion.bash / git-prompt.sh
      #
      if [ -f {{ local_home }}/git-prompt.sh ]; then
          source {{ local_home }}/git-prompt.sh
      fi
      GIT_PS1_SHOWDIRTYSTATE=true
      GIT_PS1_SHOWUNTRACKEDFILES=true
      GIT_PS1_SHOWSTASHSTATE=true
      GIT_PS1_SHOWUPSTREAM=auto
    marker: "# {mark} ANSIBLE MANAGED BLOCK(git prompt)"
  become: no
  tags:
    - git
