---
- name: install node and npm
  apt:
    name:
      - nodejs
      - npm
  tags:
    - node

- name: install n
  npm:
    name: n
    global: yes
  tags:
    - node

- name: install lts version node
  command:
    cmd: n lts
  tags:
    - node

- name: uninstall node and npm
  apt:
    name:
      - nodejs
      - npm
    state: absent
    purge: yes
  tags:
    - node

- name: install firebase-tools
  npm:
    name: firebase-tools
    global: yes
  tags:
    - node
    - firebase
