---
# tasks file for video-tools
- name: add smplayer repo
  apt_repository:
    repo: "ppa:rvm/smplayer"
  tags: video

- name: install SMPlayer
  apt:
    name: ['smplayer','smplayer-themes','smplayer-skins']
    update_cache: yes
  tags: video

- name: install vlc
  snap:
    name: vlc
  tags:
    - video
    - snap

- name: install makemkv
  snap:
    name: makemkv
  tags:
    - video
    - snap

- name: Install youtube-dl
  homebrew:
    name: youtube-dl
  environment:
    PATH: "{{ local_home }}/.linuxbrew/bin:{{ ansible_env.PATH }}"
  become: no
  tags: video

- name: add HandBrake repository
  apt_repository:
    repo: "ppa:stebbins/handbrake-releases"
  tags: handbrake

- name: install handbrake-gtk
  apt:
    name: ['handbrake-gtk']
    update_cache: yes
  tags: handbrake
