---
# tasks file for git
- name: add git repository
  apt_repository:
    repo: "ppa:git-core/ppa"
- name: install git and other tools
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - git
    - git-gui
    - meld
    - git-flow

- name: setting up git config
  template:
    src: "templates/gitconfig.j2"
    dest: "{{ home_dir }}/.gitconfig"

- name: setting up gitignore_global
  template:
    src: "templates/gitignore_global.j2"
    dest: "{{ home_dir }}/.gitignore_global"

- name: clone git-secrets from aws github repo
  git:
    repo: 'git@github.com:awslabs/git-secrets.git'
    dest: "{{ home_dir }}/git-secrets"
