---
# tasks file for tools
- name: add apt repos
  apt_repository:
    repo: "{{ item }}"
  with_items:
  - 'ppa:teejee2008/ppa' # for ukuu

- name: install tools
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - dconf-editor
  - gnome-tweaks
  - htop
  - ukuu
  - gnome-shell-pomodoro
  - clipit
