FROM ubuntu:bionic

RUN apt-get update && apt-get dist-upgrade -y && apt-get install -y software-properties-common

RUN apt-add-repository -y ppa:ansible/ansible && apt-get update && apt-get install -y \
  ansible \
  curl \

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

CMD ["/bin/bash"]