---
# tasks file for network-tools and firewall
- name: install net work tools
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - speedtest-cli
      - net-tools
      - whois
      - ufw
      - gufw

- name: set up ufw
  ufw:
    state: enabled

- name: Allow access to some TCP ports (for development)
  ufw:
    rule: allow
    to_port: "{{ item }}"
    proto: tcp
    src: 0.0.0.0/0
  with_items:
    - 4200
    - 4201
    - 8080
    - 8081

- name: Allow all access to dropbox(only accesible inside home)
  ufw:
    rule: allow
    port: 17500
    proto: "{{ item }}"
    src: 0.0.0.0/0
  with_items:
    - tcp
    - udp

