---
# tasks file for video-tools
- name: add smplayer repo
  apt_repository:
    repo: "ppa:rvm/smplayer"

- name: install SMPlayer
  apt:
    name: ['smplayer','smplayer-themes','smplayer-skins']
    update_cache: yes

- name: install devede
  apt:
    name: devede
    update_cache: yes

- name: install ffmpeg
  apt:
    name: ffmpeg
    update_cache: yes

- name: add makemkv repository
  apt_repository:
    repo: "ppa:heyarje/makemkv-beta"

- name: install makemkv
  apt:
    name: ['makemkv-oss','makemkv-bin']
    update_cache: yes

